title: Metadata Extractor
description: Extracts PDF file metadata using exiftool and saves data as key value pairs on DocumentCloud. 
instructions: ''
type: object
documents:
  - selected
  - query
properties: {}
categories: 
  - extraction
# Acceptable categories are premium, ai, export, bulk, file,  monitor, statistical, and extraction. 
# You can read more about DocumentCloud Add-On categories here: https://www.documentcloud.org/help/add-ons#types-of-add-ons
version: 2
